import type { AnswerOption, GuestConfig } from "../types";

export const singleAnswerOptions: AnswerOption[] = [
  { id: "single-yes", label: "Да.", requiresEmail: true },
  { id: "single-no", label: "Нет.", requiresEmail: false },
];

export const plusOneAnswerOptions: AnswerOption[] = [
  { id: "plus-one-yes", label: "Да.", requiresEmail: true },
  { id: "plus-one-yes-plus", label: "Да, и возьму с собой +1.", requiresEmail: true, requiresPlusOneName: true },
  { id: "plus-one-no", label: "Нет.", requiresEmail: false },
];

export const coupleAnswerOptions: AnswerOption[] = [
  { id: "couple-yes", label: "Да, будем вдвоем.", requiresEmail: true },
  { id: "couple-partial", label: "Да, приедет один из нас.", requiresEmail: true },
  { id: "couple-no", label: "Нет.", requiresEmail: false },
];

export const familyAnswerOptions: AnswerOption[] = [
  { id: "family-yes", label: "Да, будем всей семьей.", requiresEmail: true },
  { id: "family-partial", label: "Да, но приедет часть семьи.", requiresEmail: true, requiresGuestCount: true },
  { id: "family-no", label: "Нет.", requiresEmail: false },
];

export const fallbackGuest: GuestConfig = {
  slug: "general",
  guestId: "fallback",
  displayName: "Дорогие гости",
  greeting: "Дорогие гости",
  inviteType: "group",
  answerOptions: singleAnswerOptions,
};

export const guests: GuestConfig[] = [
  {
    slug: "ivanovy-a8f3",
    guestId: "guest-ivanovy",
    displayName: "семья Ивановых",
    greeting: "Дорогие Ивановы",
    inviteType: "family",
    answerOptions: familyAnswerOptions,
  },
  {
    slug: "alexey-maria-9k2m",
    guestId: "guest-alexey-maria",
    displayName: "Алексей и Мария",
    greeting: "Дорогие Алексей и Мария",
    inviteType: "couple",
    answerOptions: coupleAnswerOptions,
  },
  {
    slug: "potiridi",
    guestId: "guest-potiridi",
    displayName: "Галина и Виктор",
    greeting: "Дорогие Галина и Виктор",
    inviteType: "couple",
    answerOptions: coupleAnswerOptions,
  },
  {
    slug: "parents",
    guestId: "guest-parents",
    displayName: "Лилия и Сергей",
    greeting: "Дорогие Лилия и Сергей",
    inviteType: "couple",
    answerOptions: coupleAnswerOptions,
  },
  {
    slug: "thecrew",
    guestId: "guest-thecrew",
    displayName: "Алексей",
    greeting: "Дорогой Алексей",
    inviteType: "single",
    answerOptions: singleAnswerOptions,
  },
  {
    slug: "krestianko",
    guestId: "guest-krestianko",
    displayName: "Дарья и Дмитрий",
    greeting: "Дорогие Дарья и Дмитрий",
    inviteType: "couple",
    answerOptions: coupleAnswerOptions,
  },
  {
    slug: "stiven",
    guestId: "guest-stiven",
    displayName: "Степан",
    greeting: "Дорогой Степан",
    inviteType: "single",
    answerOptions: singleAnswerOptions,
  },
  {
    slug: "khalilove",
    guestId: "guest-khalilove",
    displayName: "Артём",
    greeting: "Дорогой Артём",
    inviteType: "single",
    answerOptions: singleAnswerOptions,
  },
  {
    slug: "julia&alex",
    guestId: "guest-julia-alex",
    displayName: "Юлия и Алексей",
    greeting: "Дорогие Юлия и Алексей",
    inviteType: "couple",
    answerOptions: coupleAnswerOptions,
  },
  {
    slug: "cornergangs",
    guestId: "guest-cornergangs",
    displayName: "Анна и Никита",
    greeting: "Дорогие Анна и Никита",
    inviteType: "couple",
    answerOptions: coupleAnswerOptions,
  },
  {
    slug: "homies",
    guestId: "guest-homies",
    displayName: "Светлана и Дмитрий",
    greeting: "Дорогие Светлана и Дмитрий",
    inviteType: "couple",
    answerOptions: coupleAnswerOptions,
  },
  {
    slug: "faraons",
    guestId: "guest-faraons",
    displayName: "Анна и Иван",
    greeting: "Дорогие Анна и Иван",
    inviteType: "couple",
    answerOptions: coupleAnswerOptions,
  },
  {
    slug: "kitty",
    guestId: "guest-kitty",
    displayName: "Анастасия",
    greeting: "Дорогая Анастасия",
    inviteType: "single",
    answerOptions: singleAnswerOptions,
  },
  {
    slug: "mainsqueezes",
    guestId: "guest-mainsqueezes",
    displayName: "Ирина и Дмитрий",
    greeting: "Дорогие Ирина и Дмитрий",
    inviteType: "couple",
    answerOptions: coupleAnswerOptions,
  },
  {
    slug: "shatalov",
    guestId: "guest-shatalov",
    displayName: "Владимир",
    greeting: "Дорогой Владимир",
    inviteType: "single",
    answerOptions: singleAnswerOptions,
  },
  {
    slug: "mistress",
    guestId: "guest-mistress",
    displayName: "Анна",
    greeting: "Дорогая Анна",
    inviteType: "single",
    answerOptions: singleAnswerOptions,
  },
  {
    slug: "margo",
    guestId: "guest-margo",
    displayName: "Маргарита",
    greeting: "Дорогая Маргарита",
    inviteType: "single",
    answerOptions: singleAnswerOptions,
  },
  {
    slug: "ladykhovankina",
    guestId: "guest-ladykhovankina",
    displayName: "Анна",
    greeting: "Дорогая Анна",
    inviteType: "single",
    answerOptions: singleAnswerOptions,
  },
  {
    slug: "ankashark",
    guestId: "guest-ankashark",
    displayName: "Анна",
    greeting: "Дорогая Анна",
    inviteType: "single",
    answerOptions: singleAnswerOptions,
  },
  {
    slug: "igorek",
    guestId: "guest-igorek",
    displayName: "Игорь",
    greeting: "Дорогой Игорь",
    inviteType: "single",
    answerOptions: singleAnswerOptions,
  },
  {
    slug: "vlados",
    guestId: "guest-vlados",
    displayName: "Владислав",
    greeting: "Дорогой Владислав",
    inviteType: "single",
    answerOptions: singleAnswerOptions,
  },
  {
    slug: "akimovy",
    guestId: "guest-akimovy",
    displayName: "Алёна и Тим",
    greeting: "Дорогие Алёна и Тим",
    inviteType: "couple",
    answerOptions: coupleAnswerOptions,
  },
  {
    slug: "sister",
    guestId: "guest-sister",
    displayName: "Мария и Максим",
    greeting: "Дорогие Мария и Максим",
    inviteType: "couple",
    answerOptions: coupleAnswerOptions,
  },
];
